package com.mark.arqhexexample.infrastructure.adapter.input.rest.mapper;

import com.mark.arqhexexample.domain.model.Product;
import com.mark.arqhexexample.infrastructure.adapter.input.rest.dto.ProductRequestDTO;
import com.mark.arqhexexample.infrastructure.adapter.input.rest.dto.ProductResponseDTO;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@Component
public class ProductApiMapper {

    public Product toDomain(ProductRequestDTO productRequestDTO) {
        return new Product(
                null, // ID will be generated by the database
                productRequestDTO.name(),
                productRequestDTO.description(),
                productRequestDTO.price(),
                productRequestDTO.sku(),
                productRequestDTO.stock(),
                productRequestDTO.imageUrl()
        );
    }

    public ProductResponseDTO toResponseDto(Product product) {
        return new ProductResponseDTO(
                product.getId(),
                product.getName(),
                product.getDescription(),
                product.getPrice(),
                product.getSku(),
                product.getStock(),
                product.getImageUrl()
        );
    }

    public List<ProductResponseDTO> toResponseDtoList(List<Product> products) {
        return products.stream()
                .map(this::toResponseDto)
                .collect(Collectors.toList());
    }
}
